<?php include "header.php"; ?>
<?php include "my_bag.php"; ?>
<div class="container mb-2">
  <div class="col-xs-12 col-md-3">
    <h4>MENÚ</h4>
    <?php include "views/nav_sidebar.php"; ?>
    <?php 
    if (FILTER_SIDEBAR) {
    ?>
      <h4 class="mt-2"><?=Lenguajes::consultarFrase("FILTERS", $_SESSION["lenguaje"])?></h4>
      <?php filters($categorias_padre); 
    }?>
    <?php 
      if (COLECCIONES_SIDEBAR) {
      ?>
    <h4 class="mt-2"><?=Lenguajes::consultarFrase("COLLECTIONS", $_SESSION["lenguaje"])?></h4>
    <?php collections($colecciones); 
    }?>
  </div>
  <div class="col-xs-12 offset-md-2 col-md-5 my-3">
    <h1>REGISTRO DE USUARIO</h1>
    <hr>
    <form method="post">
      <div class="form-group">
        <label for="exampleInputEmail1">Nombre</label>
        <input type="text" class="form-control" name="nombre" aria-describedby="emailHelp" placeholder="" required="required">      
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Apellido</label>
        <input type="text" class="form-control" name="apellido" aria-describedby="emailHelp" placeholder="" required="required">
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Número de Identificación</label>
        <input type="text" class="form-control" name="num_identificacion" aria-describedby="emailHelp" placeholder="" required="required">      
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="" required="required" value="<?=$_POST["email"]?>">   
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Empresa</label>
        <input type="text" class="form-control" name="empresa" aria-describedby="emailHelp" placeholder="">      
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">País</label>
        <select class="form-control" name="pais" id="pais" required="required">
          <option value=''>SELECCIONE</option>
          <option value='COLOMBIA' selected>COLOMBIA</option>
          <option value='AFGANISTAN'>AFGANISTAN</option>
          <option value='ALBANIA'>ALBANIA</option>
          <option value='ALEMANIA'>ALEMANIA</option>
          <option value='ANDORRA'>ANDORRA</option>
          <option value='ANGOLA'>ANGOLA</option>
          <option value='ANGUILLA'>ANGUILLA</option>
          <option value='ANTIGUA Y BARBUDA'>ANTIGUA Y BARBUDA</option>
          <option value='ANTILLAS HOLANDESAS'>ANTILLAS HOLANDESAS</option>
          <option value='ARABIA SAUDI'>ARABIA SAUDI</option>
          <option value='ARGELIA'>ARGELIA</option>
          <option value='ARGENTINA'>ARGENTINA</option>
          <option value='ARMENIA'>ARMENIA</option>
          <option value='ARUBA'>ARUBA</option>
          <option value='AUSTRALIA'>AUSTRALIA</option>
          <option value='AUSTRIA'>AUSTRIA</option>
          <option value='AZERBAIYAN'>AZERBAIYAN</option>
          <option value='BAHAMAS'>BAHAMAS</option>
          <option value='BAHREIN'>BAHREIN</option>
          <option value='BANGLADESH'>BANGLADESH</option>
          <option value='BARBADOS'>BARBADOS</option>
          <option value='BELARUS'>BELARUS</option>
          <option value='BELGICA'>BELGICA</option>
          <option value='BELICE'>BELICE</option>
          <option value='BENIN'>BENIN</option>
          <option value='BERMUDAS'>BERMUDAS</option>
          <option value='BHUTÁN'>BHUTÁN</option>
          <option value='BOLIVIA'>BOLIVIA</option>
          <option value='BOSNIA Y HERZEGOVINA'>BOSNIA Y HERZEGOVINA</option>
          <option value='BOTSWANA'>BOTSWANA</option>
          <option value='BRASIL'>BRASIL</option>
          <option value='BRUNEI'>BRUNEI</option>
          <option value='BULGARIA'>BULGARIA</option>
          <option value='BURKINA FASO'>BURKINA FASO</option>
          <option value='BURUNDI'>BURUNDI</option>
          <option value='CABO VERDE'>CABO VERDE</option>
          <option value='CAMBOYA'>CAMBOYA</option>
          <option value='CAMERUN'>CAMERUN</option>
          <option value='CANADA'>CANADA</option>
          <option value='CHAD'>CHAD</option>
          <option value='CHILE'>CHILE</option>
          <option value='CHINA'>CHINA</option>
          <option value='CHIPRE'>CHIPRE</option>
          <option value='COLOMBIA'>COLOMBIA</option>
          <option value='COMORES'>COMORES</option>
          <option value='CONGO'>CONGO</option>
          <option value='COREA'>COREA</option>
          <option value='COREA DEL NORTE '>COREA DEL NORTE </option>
          <option value='COSTA DE MARFIL'>COSTA DE MARFIL</option>
          <option value='COSTA RICA'>COSTA RICA</option>
          <option value='CROACIA'>CROACIA</option>
          <option value='CUBA'>CUBA</option>
          <option value='DINAMARCA'>DINAMARCA</option>
          <option value='DJIBOUTI'>DJIBOUTI</option>
          <option value='DOMINICA'>DOMINICA</option>
          <option value='ECUADOR'>ECUADOR</option>
          <option value='EGIPTO'>EGIPTO</option>
          <option value='EL SALVADOR'>EL SALVADOR</option>
          <option value='EMIRATOS ARABES UNIDOS'>EMIRATOS ARABES UNIDOS</option>
          <option value='ERITREA'>ERITREA</option>
          <option value='ESLOVENIA'>ESLOVENIA</option>
          <option value='ESPAÑA'>ESPAÑA</option>
          <option value='ESTADOS UNIDOS DE AMERICA'>ESTADOS UNIDOS DE AMERICA</option>
          <option value='ESTONIA'>ESTONIA</option>
          <option value='ETIOPIA'>ETIOPIA</option>
          <option value='FIJI'>FIJI</option>
          <option value='FILIPINAS'>FILIPINAS</option>
          <option value='FINLANDIA'>FINLANDIA</option>
          <option value='FRANCIA'>FRANCIA</option>
          <option value='GABON'>GABON</option>
          <option value='GAMBIA'>GAMBIA</option>
          <option value='GEORGIA'>GEORGIA</option>
          <option value='GHANA'>GHANA</option>
          <option value='GIBRALTAR'>GIBRALTAR</option>
          <option value='GRANADA'>GRANADA</option>
          <option value='GRECIA'>GRECIA</option>
          <option value='GROENLANDIA'>GROENLANDIA</option>
          <option value='GUADALUPE'>GUADALUPE</option>
          <option value='GUAM'>GUAM</option>
          <option value='GUATEMALA'>GUATEMALA</option>
          <option value='GUAYANA FRANCESA'>GUAYANA FRANCESA</option>
          <option value='GUERNESEY'>GUERNESEY</option>
          <option value='GUINEA'>GUINEA</option>
          <option value='GUINEA ECUATORIAL'>GUINEA ECUATORIAL</option>
          <option value='GUINEA-BISSAU'>GUINEA-BISSAU</option>
          <option value='GUYANA'>GUYANA</option>
          <option value='HAITI'>HAITI</option>
          <option value='HONDURAS'>HONDURAS</option>
          <option value='HONG KONG'>HONG KONG</option>
          <option value='HUNGRIA'>HUNGRIA</option>
          <option value='INDIA'>INDIA</option>
          <option value='INDONESIA'>INDONESIA</option>
          <option value='IRAN'>IRAN</option>
          <option value='IRAQ'>IRAQ</option>
          <option value='IRLANDA'>IRLANDA</option>
          <option value='ISLA DE MAN'>ISLA DE MAN</option>
          <option value='ISLA NORFOLK'>ISLA NORFOLK</option>
          <option value='ISLANDIA'>ISLANDIA</option>
          <option value='ISLAS ALAND'>ISLAS ALAND</option>
          <option value='ISLAS CAIMÁN'>ISLAS CAIMÁN</option>
          <option value='ISLAS COOK'>ISLAS COOK</option>
          <option value='ISLAS DEL CANAL'>ISLAS DEL CANAL</option>
          <option value='ISLAS FEROE'>ISLAS FEROE</option>
          <option value='ISLAS MALVINAS'>ISLAS MALVINAS</option>
          <option value='ISLAS MARIANAS DEL NORTE'>ISLAS MARIANAS DEL NORTE</option>
          <option value='ISLAS MARSHALL'>ISLAS MARSHALL</option>
          <option value='ISLAS PITCAIRN'>ISLAS PITCAIRN</option>
          <option value='ISLAS SALOMON'>ISLAS SALOMON</option>
          <option value='ISLAS TURCAS Y CAICOS'>ISLAS TURCAS Y CAICOS</option>
          <option value='ISLAS VIRGENES BRITANICAS'>ISLAS VIRGENES BRITANICAS</option>
          <option value='ISLAS VÍRGENES DE LOS ESTADOS UNIDOS'>ISLAS VÍRGENES DE LOS ESTADOS UNIDOS</option>
          <option value='ISRAEL'>ISRAEL</option>
          <option value='ITALIA'>ITALIA</option>
          <option value='JAMAICA'>JAMAICA</option>
          <option value='JAPON'>JAPON</option>
          <option value='JERSEY'>JERSEY</option>
          <option value='JORDANIA'>JORDANIA</option>
          <option value='KAZAJSTAN'>KAZAJSTAN</option>
          <option value='KENIA'>KENIA</option>
          <option value='KIRGUISTAN'>KIRGUISTAN</option>
          <option value='KIRIBATI'>KIRIBATI</option>
          <option value='KUWAIT'>KUWAIT</option>
          <option value='LAOS'>LAOS</option>
          <option value='LESOTHO'>LESOTHO</option>
          <option value='LETONIA'>LETONIA</option>
          <option value='LIBANO'>LIBANO</option>
          <option value='LIBERIA'>LIBERIA</option>
          <option value='LIBIA'>LIBIA</option>
          <option value='LIECHTENSTEIN'>LIECHTENSTEIN</option>
          <option value='LITUANIA'>LITUANIA</option>
          <option value='LUXEMBURGO'>LUXEMBURGO</option>
          <option value='MACAO'>MACAO</option>
          <option value='MACEDONIA '>MACEDONIA </option>
          <option value='MADAGASCAR'>MADAGASCAR</option>
          <option value='MALASIA'>MALASIA</option>
          <option value='MALAWI'>MALAWI</option>
          <option value='MALDIVAS'>MALDIVAS</option>
          <option value='MALI'>MALI</option>
          <option value='MALTA'>MALTA</option>
          <option value='MARRUECOS'>MARRUECOS</option>
          <option value='MARTINICA'>MARTINICA</option>
          <option value='MAURICIO'>MAURICIO</option>
          <option value='MAURITANIA'>MAURITANIA</option>
          <option value='MAYOTTE'>MAYOTTE</option>
          <option value='MEXICO'>MEXICO</option>
          <option value='MICRONESIA'>MICRONESIA</option>
          <option value='MOLDAVIA'>MOLDAVIA</option>
          <option value='MONACO'>MONACO</option>
          <option value='MONGOLIA'>MONGOLIA</option>
          <option value='MONTENEGRO'>MONTENEGRO</option>
          <option value='MONTSERRAT'>MONTSERRAT</option>
          <option value='MOZAMBIQUE'>MOZAMBIQUE</option>
          <option value='MYANMAR'>MYANMAR</option>
          <option value='NAMIBIA'>NAMIBIA</option>
          <option value='NAURU'>NAURU</option>
          <option value='NEPAL'>NEPAL</option>
          <option value='NICARAGUA'>NICARAGUA</option>
          <option value='NIGER'>NIGER</option>
          <option value='NIGERIA'>NIGERIA</option>
          <option value='NIUE'>NIUE</option>
          <option value='NORUEGA'>NORUEGA</option>
          <option value='NUEVA CALEDONIA'>NUEVA CALEDONIA</option>
          <option value='NUEVA ZELANDA'>NUEVA ZELANDA</option>
          <option value='OMAN'>OMAN</option>
          <option value='OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE'>OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE</option>
          <option value='OTROS PAISES O TERRITORIOS  DE SUDAMERICA'>OTROS PAISES O TERRITORIOS  DE SUDAMERICA</option>
          <option value='OTROS PAISES O TERRITORIOS DE AFRICA'>OTROS PAISES O TERRITORIOS DE AFRICA</option>
          <option value='OTROS PAISES O TERRITORIOS DE ASIA'>OTROS PAISES O TERRITORIOS DE ASIA</option>
          <option value='OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA'>OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA</option>
          <option value='OTROS PAISES O TERRITORIOS DE OCEANIA'>OTROS PAISES O TERRITORIOS DE OCEANIA</option>
          <option value='OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL'>OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL</option>
          <option value='OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA'>OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA</option>
          <option value='PAISES BAJOS'>PAISES BAJOS</option>
          <option value='PAKISTAN'>PAKISTAN</option>
          <option value='PALAOS'>PALAOS</option>
          <option value='PALESTINA'>PALESTINA</option>
          <option value='PANAMA'>PANAMA</option>
          <option value='PAPUA NUEVA GUINEA'>PAPUA NUEVA GUINEA</option>
          <option value='PARAGUAY'>PARAGUAY</option>
          <option value='PERU'>PERU</option>
          <option value='POLINESIA FRANCESA'>POLINESIA FRANCESA</option>
          <option value='POLONIA'>POLONIA</option>
          <option value='PORTUGAL'>PORTUGAL</option>
          <option value='PUERTO RICO'>PUERTO RICO</option>
          <option value='QATAR'>QATAR</option>
          <option value='REINO UNIDO'>REINO UNIDO</option>
          <option value='REP.DEMOCRATICA DEL CONGO'>REP.DEMOCRATICA DEL CONGO</option>
          <option value='REPUBLICA CENTROAFRICANA'>REPUBLICA CENTROAFRICANA</option>
          <option value='REPUBLICA CHECA'>REPUBLICA CHECA</option>
          <option value='REPUBLICA DOMINICANA'>REPUBLICA DOMINICANA</option>
          <option value='REPUBLICA ESLOVACA'>REPUBLICA ESLOVACA</option>
          <option value='REUNION'>REUNION</option>
          <option value='RUANDA'>RUANDA</option>
          <option value='RUMANIA'>RUMANIA</option>
          <option value='RUSIA'>RUSIA</option>
          <option value='SAHARA OCCIDENTAL'>SAHARA OCCIDENTAL</option>
          <option value='SAMOA'>SAMOA</option>
          <option value='SAMOA AMERICANA'>SAMOA AMERICANA</option>
          <option value='SAN BARTOLOME'>SAN BARTOLOME</option>
          <option value='SAN CRISTOBAL Y NIEVES'>SAN CRISTOBAL Y NIEVES</option>
          <option value='SAN MARINO'>SAN MARINO</option>
          <option value='SAN MARTIN (PARTE FRANCESA)'>SAN MARTIN (PARTE FRANCESA)</option>
          <option value='SAN PEDRO Y MIQUELON '>SAN PEDRO Y MIQUELON </option>
          <option value='SAN VICENTE Y LAS GRANADINAS'>SAN VICENTE Y LAS GRANADINAS</option>
          <option value='SANTA HELENA'>SANTA HELENA</option>
          <option value='SANTA LUCIA'>SANTA LUCIA</option>
          <option value='SANTA SEDE'>SANTA SEDE</option>
          <option value='SANTO TOME Y PRINCIPE'>SANTO TOME Y PRINCIPE</option>
          <option value='SENEGAL'>SENEGAL</option>
          <option value='SERBIA'>SERBIA</option>
          <option value='SEYCHELLES'>SEYCHELLES</option>
          <option value='SIERRA LEONA'>SIERRA LEONA</option>
          <option value='SINGAPUR'>SINGAPUR</option>
          <option value='SIRIA'>SIRIA</option>
          <option value='SOMALIA'>SOMALIA</option>
          <option value='SRI LANKA'>SRI LANKA</option>
          <option value='SUDAFRICA'>SUDAFRICA</option>
          <option value='SUDAN'>SUDAN</option>
          <option value='SUECIA'>SUECIA</option>
          <option value='SUIZA'>SUIZA</option>
          <option value='SURINAM'>SURINAM</option>
          <option value='SVALBARD Y JAN MAYEN'>SVALBARD Y JAN MAYEN</option>
          <option value='SWAZILANDIA'>SWAZILANDIA</option>
          <option value='TADYIKISTAN'>TADYIKISTAN</option>
          <option value='TAILANDIA'>TAILANDIA</option>
          <option value='TANZANIA'>TANZANIA</option>
          <option value='TIMOR ORIENTAL'>TIMOR ORIENTAL</option>
          <option value='TOGO'>TOGO</option>
          <option value='TOKELAU'>TOKELAU</option>
          <option value='TONGA'>TONGA</option>
          <option value='TRINIDAD Y TOBAGO'>TRINIDAD Y TOBAGO</option>
          <option value='TUNEZ'>TUNEZ</option>
          <option value='TURKMENISTAN'>TURKMENISTAN</option>
          <option value='TURQUIA'>TURQUIA</option>
          <option value='TUVALU'>TUVALU</option>
          <option value='UCRANIA'>UCRANIA</option>
          <option value='UGANDA'>UGANDA</option>
          <option value='URUGUAY'>URUGUAY</option>
          <option value='UZBEKISTAN'>UZBEKISTAN</option>
          <option value='VANUATU'>VANUATU</option>
          <option value='VENEZUELA'>VENEZUELA</option>
          <option value='VIETNAM'>VIETNAM</option>
          <option value='WALLIS Y FORTUNA'>WALLIS Y FORTUNA</option>
          <option value='YEMEN'>YEMEN</option>
          <option value='ZAMBIA'>ZAMBIA</option>
          <option value='ZIMBABWE'>ZIMBABWE</option>

        </select>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Ciudad</label>
        <select name="ciudadco" id="ciudadco" class="form-control" required>
          <option value=''>SELECCIONE</option>
          <option value='ABEJORRAL'>ABEJORRAL</option>
          <option value='ABREGO'>ABREGO</option>
          <option value='ABRIAQUI'>ABRIAQUI</option>
          <option value='ACACIAS'>ACACIAS</option>
          <option value='ACANDI'>ACANDI</option>
          <option value='ACEVEDO'>ACEVEDO</option>
          <option value='ACHI'>ACHI</option>
          <option value='AGRADO'>AGRADO</option>
          <option value='AGUA DE DIOS'>AGUA DE DIOS</option>
          <option value='AGUACHICA'>AGUACHICA</option>
          <option value='AGUADA'>AGUADA</option>
          <option value='AGUADAS'>AGUADAS</option>
          <option value='AGUAZUL'>AGUAZUL</option>
          <option value='AGUSTIN CODAZZI'>AGUSTIN CODAZZI</option>
          <option value='AIPE'>AIPE</option>
          <option value='ALBAN'>ALBAN</option>
          <option value='ALBAN'>ALBAN</option>
          <option value='ALBANIA'>ALBANIA</option>
          <option value='ALBANIA'>ALBANIA</option>
          <option value='ALBANIA'>ALBANIA</option>
          <option value='ALCALA'>ALCALA</option>
          <option value='ALDANA'>ALDANA</option>
          <option value='ALEJANDRIA'>ALEJANDRIA</option>
          <option value='ALGARROBO'>ALGARROBO</option>
          <option value='ALGECIRAS'>ALGECIRAS</option>
          <option value='ALMAGUER'>ALMAGUER</option>
          <option value='ALMEIDA'>ALMEIDA</option>
          <option value='ALPUJARRA'>ALPUJARRA</option>
          <option value='ALTAMIRA'>ALTAMIRA</option>
          <option value='ALTO BAUDO'>ALTO BAUDO</option>
          <option value='ALTOS DEL ROSARIO'>ALTOS DEL ROSARIO</option>
          <option value='ALVARADO'>ALVARADO</option>
          <option value='AMAGA'>AMAGA</option>
          <option value='AMALFI'>AMALFI</option>
          <option value='AMBALEMA'>AMBALEMA</option>
          <option value='ANAPOIMA'>ANAPOIMA</option>
          <option value='ANCUYA'>ANCUYA</option>
          <option value='ANDALUCIA'>ANDALUCIA</option>
          <option value='ANDES'>ANDES</option>
          <option value='ANGELOPOLIS'>ANGELOPOLIS</option>
          <option value='ANGOSTURA'>ANGOSTURA</option>
          <option value='ANOLAIMA'>ANOLAIMA</option>
          <option value='ANORI'>ANORI</option>
          <option value='ANSERMA'>ANSERMA</option>
          <option value='ANSERMANUEVO'>ANSERMANUEVO</option>
          <option value='ANZA'>ANZA</option>
          <option value='ANZOATEGUI'>ANZOATEGUI</option>
          <option value='APARTADO'>APARTADO</option>
          <option value='APIA'>APIA</option>
          <option value='APULO'>APULO</option>
          <option value='AQUITANIA'>AQUITANIA</option>
          <option value='ARACATACA'>ARACATACA</option>
          <option value='ARANZAZU'>ARANZAZU</option>
          <option value='ARATOCA'>ARATOCA</option>
          <option value='ARAUCA'>ARAUCA</option>
          <option value='ARAUQUITA'>ARAUQUITA</option>
          <option value='ARBELAEZ'>ARBELAEZ</option>
          <option value='ARBOLEDA'>ARBOLEDA</option>
          <option value='ARBOLEDAS'>ARBOLEDAS</option>
          <option value='ARBOLETES'>ARBOLETES</option>
          <option value='ARCABUCO'>ARCABUCO</option>
          <option value='ARENAL'>ARENAL</option>
          <option value='ARGELIA'>ARGELIA</option>
          <option value='ARGELIA'>ARGELIA</option>
          <option value='ARGELIA'>ARGELIA</option>
          <option value='ARIGUANI'>ARIGUANI</option>
          <option value='ARJONA'>ARJONA</option>
          <option value='ARMENIA'>ARMENIA</option>
          <option value='ARMENIA'>ARMENIA</option>
          <option value='ARMERO'>ARMERO</option>
          <option value='ARROYOHONDO'>ARROYOHONDO</option>
          <option value='ASTREA'>ASTREA</option>
          <option value='ATACO'>ATACO</option>
          <option value='ATRATO'>ATRATO</option>
          <option value='AYAPEL'>AYAPEL</option>
          <option value='BAGADO'>BAGADO</option>
          <option value='BAHIA SOLANO'>BAHIA SOLANO</option>
          <option value='BAJO BAUDO'>BAJO BAUDO</option>
          <option value='BALBOA'>BALBOA</option>
          <option value='BALBOA'>BALBOA</option>
          <option value='BARANOA'>BARANOA</option>
          <option value='BARAYA'>BARAYA</option>
          <option value='BARBACOAS'>BARBACOAS</option>
          <option value='BARBOSA'>BARBOSA</option>
          <option value='BARBOSA'>BARBOSA</option>
          <option value='BARICHARA'>BARICHARA</option>
          <option value='BARRANCA DE UPIA'>BARRANCA DE UPIA</option>
          <option value='BARRANCABERMEJA'>BARRANCABERMEJA</option>
          <option value='BARRANCAS'>BARRANCAS</option>
          <option value='BARRANCO DE LOBA'>BARRANCO DE LOBA</option>
          <option value='BARRANCO MINAS'>BARRANCO MINAS</option>
          <option value='BARRANQUILLA'>BARRANQUILLA</option>
          <option value='BECERRIL'>BECERRIL</option>
          <option value='BELALCAZAR'>BELALCAZAR</option>
          <option value='BELEN'>BELEN</option>
          <option value='BELEN'>BELEN</option>
          <option value='BELEN DE LOS ANDAQUIES'>BELEN DE LOS ANDAQUIES</option>
          <option value='BELEN DE UMBRIA'>BELEN DE UMBRIA</option>
          <option value='BELLO'>BELLO</option>
          <option value='BELMIRA'>BELMIRA</option>
          <option value='BELTRAN'>BELTRAN</option>
          <option value='BERBEO'>BERBEO</option>
          <option value='BETANIA'>BETANIA</option>
          <option value='BETEITIVA'>BETEITIVA</option>
          <option value='BETULIA'>BETULIA</option>
          <option value='BETULIA'>BETULIA</option>
          <option value='BITUIMA'>BITUIMA</option>
          <option value='BOAVITA'>BOAVITA</option>
          <option value='BOCHALEMA'>BOCHALEMA</option>
          <option value='BOGOTA'>BOGOTA, D.C.</option>
          <option value='BOJACA'>BOJACA</option>
          <option value='BOJAYA'>BOJAYA</option>
          <option value='BOLIVAR'>BOLIVAR</option>
          <option value='BOLIVAR'>BOLIVAR</option>
          <option value='BOLIVAR'>BOLIVAR</option>
          <option value='BOSCONIA'>BOSCONIA</option>
          <option value='BOYACA'>BOYACA</option>
          <option value='BRICEÑO'>BRICEÑO</option>
          <option value='BRICEÑO'>BRICEÑO</option>
          <option value='BUCARAMANGA'>BUCARAMANGA</option>
          <option value='BUCARASICA'>BUCARASICA</option>
          <option value='BUENAVENTURA'>BUENAVENTURA</option>
          <option value='BUENAVISTA'>BUENAVISTA</option>
          <option value='BUENAVISTA'>BUENAVISTA</option>
          <option value='BUENAVISTA'>BUENAVISTA</option>
          <option value='BUENAVISTA'>BUENAVISTA</option>
          <option value='BUENOS AIRES'>BUENOS AIRES</option>
          <option value='BUESACO'>BUESACO</option>
          <option value='BUGALAGRANDE'>BUGALAGRANDE</option>
          <option value='BURITICA'>BURITICA</option>
          <option value='BUSBANZA'>BUSBANZA</option>
          <option value='CABRERA'>CABRERA</option>
          <option value='CABRERA'>CABRERA</option>
          <option value='CABUYARO'>CABUYARO</option>
          <option value='CACAHUAL'>CACAHUAL</option>
          <option value='CACERES'>CACERES</option>
          <option value='CACHIPAY'>CACHIPAY</option>
          <option value='CACHIRA'>CACHIRA</option>
          <option value='CACOTA'>CACOTA</option>
          <option value='CAICEDO'>CAICEDO</option>
          <option value='CAICEDONIA'>CAICEDONIA</option>
          <option value='CAIMITO'>CAIMITO</option>
          <option value='CAJAMARCA'>CAJAMARCA</option>
          <option value='CAJIBIO'>CAJIBIO</option>
          <option value='CAJICA'>CAJICA</option>
          <option value='CALAMAR'>CALAMAR</option>
          <option value='CALAMAR'>CALAMAR</option>
          <option value='CALARCA'>CALARCA</option>
          <option value='CALDAS'>CALDAS</option>
          <option value='CALDAS'>CALDAS</option>
          <option value='CALDONO'>CALDONO</option>
          <option value='CALI'>CALI</option>
          <option value='CALIFORNIA'>CALIFORNIA</option>
          <option value='CALIMA'>CALIMA</option>
          <option value='CALOTO'>CALOTO</option>
          <option value='CAMPAMENTO'>CAMPAMENTO</option>
          <option value='CAMPO DE LA CRUZ'>CAMPO DE LA CRUZ</option>
          <option value='CAMPOALEGRE'>CAMPOALEGRE</option>
          <option value='CAMPOHERMOSO'>CAMPOHERMOSO</option>
          <option value='CANALETE'>CANALETE</option>
          <option value='CANDELARIA'>CANDELARIA</option>
          <option value='CANDELARIA'>CANDELARIA</option>
          <option value='CANTAGALLO'>CANTAGALLO</option>
          <option value='CAÑASGORDAS'>CAÑASGORDAS</option>
          <option value='CAPARRAPI'>CAPARRAPI</option>
          <option value='CAPITANEJO'>CAPITANEJO</option>
          <option value='CAQUEZA'>CAQUEZA</option>
          <option value='CARACOLI'>CARACOLI</option>
          <option value='CARAMANTA'>CARAMANTA</option>
          <option value='CARCASI'>CARCASI</option>
          <option value='CAREPA'>CAREPA</option>
          <option value='CARMEN DE APICALA'>CARMEN DE APICALA</option>
          <option value='CARMEN DE CARUPA'>CARMEN DE CARUPA</option>
          <option value='CARMEN DEL DARIEN'>CARMEN DEL DARIEN</option>
          <option value='CAROLINA'>CAROLINA</option>
          <option value='CARTAGENA'>CARTAGENA</option>
          <option value='CARTAGENA DEL CHAIRA'>CARTAGENA DEL CHAIRA</option>
          <option value='CARTAGO'>CARTAGO</option>
          <option value='CARURU'>CARURU</option>
          <option value='CASABIANCA'>CASABIANCA</option>
          <option value='CASTILLA LA NUEVA'>CASTILLA LA NUEVA</option>
          <option value='CAUCASIA'>CAUCASIA</option>
          <option value='CEPITA'>CEPITA</option>
          <option value='CERETE'>CERETE</option>
          <option value='CERINZA'>CERINZA</option>
          <option value='CERRITO'>CERRITO</option>
          <option value='CERRO SAN ANTONIO'>CERRO SAN ANTONIO</option>
          <option value='CERTEGUI'>CERTEGUI</option>
          <option value='CHACHAGsI'>CHACHAGsI</option>
          <option value='CHAGUANI'>CHAGUANI</option>
          <option value='CHALAN'>CHALAN</option>
          <option value='CHAMEZA'>CHAMEZA</option>
          <option value='CHAPARRAL'>CHAPARRAL</option>
          <option value='CHARALA'>CHARALA</option>
          <option value='CHARTA'>CHARTA</option>
          <option value='CHIA'>CHIA</option>
          <option value='CHIBOLO'>CHIBOLO</option>
          <option value='CHIGORODO'>CHIGORODO</option>
          <option value='CHIMA'>CHIMA</option>
          <option value='CHIMA'>CHIMA</option>
          <option value='CHIMICHAGUA'>CHIMICHAGUA</option>
          <option value='CHINACOTA'>CHINACOTA</option>
          <option value='CHINAVITA'>CHINAVITA</option>
          <option value='CHINCHINA'>CHINCHINA</option>
          <option value='CHINU'>CHINU</option>
          <option value='CHIPAQUE'>CHIPAQUE</option>
          <option value='CHIPATA'>CHIPATA</option>
          <option value='CHIQUINQUIRA'>CHIQUINQUIRA</option>
          <option value='CHIQUIZA'>CHIQUIZA</option>
          <option value='CHIRIGUANA'>CHIRIGUANA</option>
          <option value='CHISCAS'>CHISCAS</option>
          <option value='CHITA'>CHITA</option>
          <option value='CHITAGA'>CHITAGA</option>
          <option value='CHITARAQUE'>CHITARAQUE</option>
          <option value='CHIVATA'>CHIVATA</option>
          <option value='CHIVOR'>CHIVOR</option>
          <option value='CHOACHI'>CHOACHI</option>
          <option value='CHOCONTA'>CHOCONTA</option>
          <option value='CICUCO'>CICUCO</option>
          <option value='CIENAGA'>CIENAGA</option>
          <option value='CIENAGA DE ORO'>CIENAGA DE ORO</option>
          <option value='CIENEGA'>CIENEGA</option>
          <option value='CIMITARRA'>CIMITARRA</option>
          <option value='CIRCASIA'>CIRCASIA</option>
          <option value='CISNEROS'>CISNEROS</option>
          <option value='CIUDAD BOLIVAR'>CIUDAD BOLIVAR</option>
          <option value='CLEMENCIA'>CLEMENCIA</option>
          <option value='COCORNA'>COCORNA</option>
          <option value='COELLO'>COELLO</option>
          <option value='COGUA'>COGUA</option>
          <option value='COLOMBIA'>COLOMBIA</option>
          <option value='COLON'>COLON</option>
          <option value='COLON'>COLON</option>
          <option value='COLOSO'>COLOSO</option>
          <option value='COMBITA'>COMBITA</option>
          <option value='CONCEPCION'>CONCEPCION</option>
          <option value='CONCEPCION'>CONCEPCION</option>
          <option value='CONCORDIA'>CONCORDIA</option>
          <option value='CONCORDIA'>CONCORDIA</option>
          <option value='CONDOTO'>CONDOTO</option>
          <option value='CONFINES'>CONFINES</option>
          <option value='CONSACA'>CONSACA</option>
          <option value='CONTADERO'>CONTADERO</option>
          <option value='CONTRATACION'>CONTRATACION</option>
          <option value='CONVENCION'>CONVENCION</option>
          <option value='COPACABANA'>COPACABANA</option>
          <option value='COPER'>COPER</option>
          <option value='CORDOBA'>CORDOBA</option>
          <option value='CORDOBA'>CORDOBA</option>
          <option value='CORDOBA'>CORDOBA</option>
          <option value='CORINTO'>CORINTO</option>
          <option value='COROMORO'>COROMORO</option>
          <option value='COROZAL'>COROZAL</option>
          <option value='CORRALES'>CORRALES</option>
          <option value='COTA'>COTA</option>
          <option value='COTORRA'>COTORRA</option>
          <option value='COVARACHIA'>COVARACHIA</option>
          <option value='COVEÑAS'>COVEÑAS</option>
          <option value='COYAIMA'>COYAIMA</option>
          <option value='CRAVO NORTE'>CRAVO NORTE</option>
          <option value='CUASPUD'>CUASPUD</option>
          <option value='CUBARA'>CUBARA</option>
          <option value='CUBARRAL'>CUBARRAL</option>
          <option value='CUCAITA'>CUCAITA</option>
          <option value='CUCUNUBA'>CUCUNUBA</option>
          <option value='CUCUTA'>CUCUTA</option>
          <option value='CUCUTILLA'>CUCUTILLA</option>
          <option value='CUITIVA'>CUITIVA</option>
          <option value='CUMARAL'>CUMARAL</option>
          <option value='CUMARIBO'>CUMARIBO</option>
          <option value='CUMBAL'>CUMBAL</option>
          <option value='CUMBITARA'>CUMBITARA</option>
          <option value='CUNDAY'>CUNDAY</option>
          <option value='CURILLO'>CURILLO</option>
          <option value='CURITI'>CURITI</option>
          <option value='CURUMANI'>CURUMANI</option>
          <option value='DABEIBA'>DABEIBA</option>
          <option value='DAGUA'>DAGUA</option>
          <option value='DIBULLA'>DIBULLA</option>
          <option value='DISTRACCION'>DISTRACCION</option>
          <option value='DOLORES'>DOLORES</option>
          <option value='DON MATIAS'>DON MATIAS</option>
          <option value='DOSQUEBRADAS'>DOSQUEBRADAS</option>
          <option value='DUITAMA'>DUITAMA</option>
          <option value='DURANIA'>DURANIA</option>
          <option value='EBEJICO'>EBEJICO</option>
          <option value='EL AGUILA'>EL AGUILA</option>
          <option value='EL BAGRE'>EL BAGRE</option>
          <option value='EL BANCO'>EL BANCO</option>
          <option value='EL CAIRO'>EL CAIRO</option>
          <option value='EL CALVARIO'>EL CALVARIO</option>
          <option value='EL CANTON DEL SAN PABLO'>EL CANTON DEL SAN PABLO</option>
          <option value='EL CARMEN'>EL CARMEN</option>
          <option value='EL CARMEN DE ATRATO'>EL CARMEN DE ATRATO</option>
          <option value='EL CARMEN DE BOLIVAR'>EL CARMEN DE BOLIVAR</option>
          <option value='EL CARMEN DE CHUCURI'>EL CARMEN DE CHUCURI</option>
          <option value='EL CARMEN DE VIBORAL'>EL CARMEN DE VIBORAL</option>
          <option value='EL CASTILLO'>EL CASTILLO</option>
          <option value='EL CERRITO'>EL CERRITO</option>
          <option value='EL CHARCO'>EL CHARCO</option>
          <option value='EL COCUY'>EL COCUY</option>
          <option value='EL COLEGIO'>EL COLEGIO</option>
          <option value='EL COPEY'>EL COPEY</option>
          <option value='EL DONCELLO'>EL DONCELLO</option>
          <option value='EL DORADO'>EL DORADO</option>
          <option value='EL DOVIO'>EL DOVIO</option>
          <option value='EL ENCANTO'>EL ENCANTO</option>
          <option value='EL ESPINO'>EL ESPINO</option>
          <option value='EL GUACAMAYO'>EL GUACAMAYO</option>
          <option value='EL GUAMO'>EL GUAMO</option>
          <option value='EL LITORAL DEL SAN JUAN'>EL LITORAL DEL SAN JUAN</option>
          <option value='EL MOLINO'>EL MOLINO</option>
          <option value='EL PASO'>EL PASO</option>
          <option value='EL PAUJIL'>EL PAUJIL</option>
          <option value='EL PEÑOL'>EL PEÑOL</option>
          <option value='EL PEÑON'>EL PEÑON</option>
          <option value='EL PEÑON'>EL PEÑON</option>
          <option value='EL PEÑON'>EL PEÑON</option>
          <option value='EL PIÑON'>EL PIÑON</option>
          <option value='EL PLAYON'>EL PLAYON</option>
          <option value='EL RETEN'>EL RETEN</option>
          <option value='EL RETORNO'>EL RETORNO</option>
          <option value='EL ROBLE'>EL ROBLE</option>
          <option value='EL ROSAL'>EL ROSAL</option>
          <option value='EL ROSARIO'>EL ROSARIO</option>
          <option value='EL SANTUARIO'>EL SANTUARIO</option>
          <option value='EL TABLON DE GOMEZ'>EL TABLON DE GOMEZ</option>
          <option value='EL TAMBO'>EL TAMBO</option>
          <option value='EL TAMBO'>EL TAMBO</option>
          <option value='EL TARRA'>EL TARRA</option>
          <option value='EL ZULIA'>EL ZULIA</option>
          <option value='ELIAS'>ELIAS</option>
          <option value='ENCINO'>ENCINO</option>
          <option value='ENCISO'>ENCISO</option>
          <option value='ENTRERRIOS'>ENTRERRIOS</option>
          <option value='ENVIGADO'>ENVIGADO</option>
          <option value='ESPINAL'>ESPINAL</option>
          <option value='FACATATIVA'>FACATATIVA</option>
          <option value='FALAN'>FALAN</option>
          <option value='FILADELFIA'>FILADELFIA</option>
          <option value='FILANDIA'>FILANDIA</option>
          <option value='FIRAVITOBA'>FIRAVITOBA</option>
          <option value='FLANDES'>FLANDES</option>
          <option value='FLORENCIA'>FLORENCIA</option>
          <option value='FLORENCIA'>FLORENCIA</option>
          <option value='FLORESTA'>FLORESTA</option>
          <option value='FLORIAN'>FLORIAN</option>
          <option value='FLORIDA'>FLORIDA</option>
          <option value='FLORIDABLANCA'>FLORIDABLANCA</option>
          <option value='FOMEQUE'>FOMEQUE</option>
          <option value='FONSECA'>FONSECA</option>
          <option value='FORTUL'>FORTUL</option>
          <option value='FOSCA'>FOSCA</option>
          <option value='FRANCISCO PIZARRO'>FRANCISCO PIZARRO</option>
          <option value='FREDONIA'>FREDONIA</option>
          <option value='FRESNO'>FRESNO</option>
          <option value='FRONTINO'>FRONTINO</option>
          <option value='FUENTE DE ORO'>FUENTE DE ORO</option>
          <option value='FUNDACION'>FUNDACION</option>
          <option value='FUNES'>FUNES</option>
          <option value='FUNZA'>FUNZA</option>
          <option value='FUQUENE'>FUQUENE</option>
          <option value='FUSAGASUGA'>FUSAGASUGA</option>
          <option value='GACHALA'>GACHALA</option>
          <option value='GACHANCIPA'>GACHANCIPA</option>
          <option value='GACHANTIVA'>GACHANTIVA</option>
          <option value='GACHETA'>GACHETA</option>
          <option value='GALAN'>GALAN</option>
          <option value='GALAPA'>GALAPA</option>
          <option value='GALERAS'>GALERAS</option>
          <option value='GAMA'>GAMA</option>
          <option value='GAMARRA'>GAMARRA</option>
          <option value='GAMBITA'>GAMBITA</option>
          <option value='GAMEZA'>GAMEZA</option>
          <option value='GARAGOA'>GARAGOA</option>
          <option value='GARZON'>GARZON</option>
          <option value='GENOVA'>GENOVA</option>
          <option value='GIGANTE'>GIGANTE</option>
          <option value='GINEBRA'>GINEBRA</option>
          <option value='GIRALDO'>GIRALDO</option>
          <option value='GIRARDOT'>GIRARDOT</option>
          <option value='GIRARDOTA'>GIRARDOTA</option>
          <option value='GIRON'>GIRON</option>
          <option value='GOMEZ PLATA'>GOMEZ PLATA</option>
          <option value='GONZALEZ'>GONZALEZ</option>
          <option value='GRAMALOTE'>GRAMALOTE</option>
          <option value='GRANADA'>GRANADA</option>
          <option value='GRANADA'>GRANADA</option>
          <option value='GRANADA'>GRANADA</option>
          <option value='GsEPSA'>GsEPSA</option>
          <option value='GsICAN'>GsICAN</option>
          <option value='GUACA'>GUACA</option>
          <option value='GUACAMAYAS'>GUACAMAYAS</option>
          <option value='GUACARI'>GUACARI</option>
          <option value='GUACHENE'>GUACHENE</option>
          <option value='GUACHETA'>GUACHETA</option>
          <option value='GUACHUCAL'>GUACHUCAL</option>
          <option value='GUADALAJARA DE BUGA'>GUADALAJARA DE BUGA</option>
          <option value='GUADALUPE'>GUADALUPE</option>
          <option value='GUADALUPE'>GUADALUPE</option>
          <option value='GUADALUPE'>GUADALUPE</option>
          <option value='GUADUAS'>GUADUAS</option>
          <option value='GUAITARILLA'>GUAITARILLA</option>
          <option value='GUALMATAN'>GUALMATAN</option>
          <option value='GUAMAL'>GUAMAL</option>
          <option value='GUAMAL'>GUAMAL</option>
          <option value='GUAMO'>GUAMO</option>
          <option value='GUAPI'>GUAPI</option>
          <option value='GUAPOTA'>GUAPOTA</option>
          <option value='GUARANDA'>GUARANDA</option>
          <option value='GUARNE'>GUARNE</option>
          <option value='GUASCA'>GUASCA</option>
          <option value='GUATAPE'>GUATAPE</option>
          <option value='GUATAQUI'>GUATAQUI</option>
          <option value='GUATAVITA'>GUATAVITA</option>
          <option value='GUATEQUE'>GUATEQUE</option>
          <option value='GUATICA'>GUATICA</option>
          <option value='GUAVATA'>GUAVATA</option>
          <option value='GUAYABAL DE SIQUIMA'>GUAYABAL DE SIQUIMA</option>
          <option value='GUAYABETAL'>GUAYABETAL</option>
          <option value='GUAYATA'>GUAYATA</option>
          <option value='GUTIERREZ'>GUTIERREZ</option>
          <option value='HACARI'>HACARI</option>
          <option value='HATILLO DE LOBA'>HATILLO DE LOBA</option>
          <option value='HATO'>HATO</option>
          <option value='HATO COROZAL'>HATO COROZAL</option>
          <option value='HATONUEVO'>HATONUEVO</option>
          <option value='HELICONIA'>HELICONIA</option>
          <option value='HERRAN'>HERRAN</option>
          <option value='HERVEO'>HERVEO</option>
          <option value='HISPANIA'>HISPANIA</option>
          <option value='HOBO'>HOBO</option>
          <option value='HONDA'>HONDA</option>
          <option value='IBAGUE'>IBAGUE</option>
          <option value='ICONONZO'>ICONONZO</option>
          <option value='ILES'>ILES</option>
          <option value='IMUES'>IMUES</option>
          <option value='INIRIDA'>INIRIDA</option>
          <option value='INZA'>INZA</option>
          <option value='IPIALES'>IPIALES</option>
          <option value='IQUIRA'>IQUIRA</option>
          <option value='ISNOS'>ISNOS</option>
          <option value='ISTMINA'>ISTMINA</option>
          <option value='ITAGUI'>ITAGUI</option>
          <option value='ITUANGO'>ITUANGO</option>
          <option value='IZA'>IZA</option>
          <option value='JAMBALO'>JAMBALO</option>
          <option value='JAMUNDI'>JAMUNDI</option>
          <option value='JARDIN'>JARDIN</option>
          <option value='JENESANO'>JENESANO</option>
          <option value='JERICO'>JERICO</option>
          <option value='JERICO'>JERICO</option>
          <option value='JERUSALEN'>JERUSALEN</option>
          <option value='JESUS MARIA'>JESUS MARIA</option>
          <option value='JORDAN'>JORDAN</option>
          <option value='JUAN DE ACOSTA'>JUAN DE ACOSTA</option>
          <option value='JUNIN'>JUNIN</option>
          <option value='JURADO'>JURADO</option>
          <option value='LA APARTADA'>LA APARTADA</option>
          <option value='LA ARGENTINA'>LA ARGENTINA</option>
          <option value='LA BELLEZA'>LA BELLEZA</option>
          <option value='LA CALERA'>LA CALERA</option>
          <option value='LA CAPILLA'>LA CAPILLA</option>
          <option value='LA CEJA'>LA CEJA</option>
          <option value='LA CELIA'>LA CELIA</option>
          <option value='LA CHORRERA'>LA CHORRERA</option>
          <option value='LA CRUZ'>LA CRUZ</option>
          <option value='LA CUMBRE'>LA CUMBRE</option>
          <option value='LA DORADA'>LA DORADA</option>
          <option value='LA ESPERANZA'>LA ESPERANZA</option>
          <option value='LA ESTRELLA'>LA ESTRELLA</option>
          <option value='LA FLORIDA'>LA FLORIDA</option>
          <option value='LA GLORIA'>LA GLORIA</option>
          <option value='LA GUADALUPE'>LA GUADALUPE</option>
          <option value='LA JAGUA DE IBIRICO'>LA JAGUA DE IBIRICO</option>
          <option value='LA JAGUA DEL PILAR'>LA JAGUA DEL PILAR</option>
          <option value='LA LLANADA'>LA LLANADA</option>
          <option value='LA MACARENA'>LA MACARENA</option>
          <option value='LA MERCED'>LA MERCED</option>
          <option value='LA MESA'>LA MESA</option>
          <option value='LA MONTAÑITA'>LA MONTAÑITA</option>
          <option value='LA PALMA'>LA PALMA</option>
          <option value='LA PAZ'>LA PAZ</option>
          <option value='LA PAZ'>LA PAZ</option>
          <option value='LA PEDRERA'>LA PEDRERA</option>
          <option value='LA PEÑA'>LA PEÑA</option>
          <option value='LA PINTADA'>LA PINTADA</option>
          <option value='LA PLATA'>LA PLATA</option>
          <option value='LA PLAYA'>LA PLAYA</option>
          <option value='LA PRIMAVERA'>LA PRIMAVERA</option>
          <option value='LA SALINA'>LA SALINA</option>
          <option value='LA SIERRA'>LA SIERRA</option>
          <option value='LA TEBAIDA'>LA TEBAIDA</option>
          <option value='LA TOLA'>LA TOLA</option>
          <option value='LA UNION'>LA UNION</option>
          <option value='LA UNION'>LA UNION</option>
          <option value='LA UNION'>LA UNION</option>
          <option value='LA UNION'>LA UNION</option>
          <option value='LA UVITA'>LA UVITA</option>
          <option value='LA VEGA'>LA VEGA</option>
          <option value='LA VEGA'>LA VEGA</option>
          <option value='LA VICTORIA'>LA VICTORIA</option>
          <option value='LA VICTORIA'>LA VICTORIA</option>
          <option value='LA VICTORIA'>LA VICTORIA</option>
          <option value='LA VIRGINIA'>LA VIRGINIA</option>
          <option value='LABATECA'>LABATECA</option>
          <option value='LABRANZAGRANDE'>LABRANZAGRANDE</option>
          <option value='LANDAZURI'>LANDAZURI</option>
          <option value='LEBRIJA'>LEBRIJA</option>
          <option value='LEGUIZAMO'>LEGUIZAMO</option>
          <option value='LEIVA'>LEIVA</option>
          <option value='LEJANIAS'>LEJANIAS</option>
          <option value='LENGUAZAQUE'>LENGUAZAQUE</option>
          <option value='LERIDA'>LERIDA</option>
          <option value='LETICIA'>LETICIA</option>
          <option value='LIBANO'>LIBANO</option>
          <option value='LIBORINA'>LIBORINA</option>
          <option value='LINARES'>LINARES</option>
          <option value='LLORO'>LLORO</option>
          <option value='LOPEZ'>LOPEZ</option>
          <option value='LORICA'>LORICA</option>
          <option value='LOS ANDES'>LOS ANDES</option>
          <option value='LOS CORDOBAS'>LOS CORDOBAS</option>
          <option value='LOS PALMITOS'>LOS PALMITOS</option>
          <option value='LOS PATIOS'>LOS PATIOS</option>
          <option value='LOS SANTOS'>LOS SANTOS</option>
          <option value='LOURDES'>LOURDES</option>
          <option value='LURUACO'>LURUACO</option>
          <option value='MACANAL'>MACANAL</option>
          <option value='MACARAVITA'>MACARAVITA</option>
          <option value='MACEO'>MACEO</option>
          <option value='MACHETA'>MACHETA</option>
          <option value='MADRID'>MADRID</option>
          <option value='MAGANGUE'>MAGANGUE</option>
          <option value='MAGsI'>MAGsI</option>
          <option value='MAHATES'>MAHATES</option>
          <option value='MAICAO'>MAICAO</option>
          <option value='MAJAGUAL'>MAJAGUAL</option>
          <option value='MALAGA'>MALAGA</option>
          <option value='MALAMBO'>MALAMBO</option>
          <option value='MALLAMA'>MALLAMA</option>
          <option value='MANATI'>MANATI</option>
          <option value='MANAURE'>MANAURE</option>
          <option value='MANAURE'>MANAURE</option>
          <option value='MANI'>MANI</option>
          <option value='MANIZALES'>MANIZALES</option>
          <option value='MANTA'>MANTA</option>
          <option value='MANZANARES'>MANZANARES</option>
          <option value='MAPIRIPAN'>MAPIRIPAN</option>
          <option value='MAPIRIPANA'>MAPIRIPANA</option>
          <option value='MARGARITA'>MARGARITA</option>
          <option value='MARIA LA BAJA'>MARIA LA BAJA</option>
          <option value='MARINILLA'>MARINILLA</option>
          <option value='MARIPI'>MARIPI</option>
          <option value='MARIQUITA'>MARIQUITA</option>
          <option value='MARMATO'>MARMATO</option>
          <option value='MARQUETALIA'>MARQUETALIA</option>
          <option value='MARSELLA'>MARSELLA</option>
          <option value='MARULANDA'>MARULANDA</option>
          <option value='MATANZA'>MATANZA</option>
          <option value='MEDELLIN'>MEDELLIN</option>
          <option value='MEDINA'>MEDINA</option>
          <option value='MEDIO ATRATO'>MEDIO ATRATO</option>
          <option value='MEDIO BAUDO'>MEDIO BAUDO</option>
          <option value='MEDIO SAN JUAN'>MEDIO SAN JUAN</option>
          <option value='MELGAR'>MELGAR</option>
          <option value='MERCADERES'>MERCADERES</option>
          <option value='MESETAS'>MESETAS</option>
          <option value='MILAN'>MILAN</option>
          <option value='MIRAFLORES'>MIRAFLORES</option>
          <option value='MIRAFLORES'>MIRAFLORES</option>
          <option value='MIRANDA'>MIRANDA</option>
          <option value='MIRITI - PARANA'>MIRITI - PARANA</option>
          <option value='MISTRATO'>MISTRATO</option>
          <option value='MITU'>MITU</option>
          <option value='MOCOA'>MOCOA</option>
          <option value='MOGOTES'>MOGOTES</option>
          <option value='MOLAGAVITA'>MOLAGAVITA</option>
          <option value='MOMIL'>MOMIL</option>
          <option value='MOMPOS'>MOMPOS</option>
          <option value='MONGUA'>MONGUA</option>
          <option value='MONGUI'>MONGUI</option>
          <option value='MONIQUIRA'>MONIQUIRA</option>
          <option value='MONTEBELLO'>MONTEBELLO</option>
          <option value='MONTECRISTO'>MONTECRISTO</option>
          <option value='MONTELIBANO'>MONTELIBANO</option>
          <option value='MONTENEGRO'>MONTENEGRO</option>
          <option value='MONTERIA'>MONTERIA</option>
          <option value='MONTERREY'>MONTERREY</option>
          <option value='MOÑITOS'>MOÑITOS</option>
          <option value='MORALES'>MORALES</option>
          <option value='MORALES'>MORALES</option>
          <option value='MORELIA'>MORELIA</option>
          <option value='MORICHAL'>MORICHAL</option>
          <option value='MORROA'>MORROA</option>
          <option value='MOSQUERA'>MOSQUERA</option>
          <option value='MOSQUERA'>MOSQUERA</option>
          <option value='MOTAVITA'>MOTAVITA</option>
          <option value='MURILLO'>MURILLO</option>
          <option value='MURINDO'>MURINDO</option>
          <option value='MUTATA'>MUTATA</option>
          <option value='MUTISCUA'>MUTISCUA</option>
          <option value='MUZO'>MUZO</option>
          <option value='NARIÑO'>NARIÑO</option>
          <option value='NARIÑO'>NARIÑO</option>
          <option value='NARIÑO'>NARIÑO</option>
          <option value='NATAGA'>NATAGA</option>
          <option value='NATAGAIMA'>NATAGAIMA</option>
          <option value='NECHI'>NECHI</option>
          <option value='NECOCLI'>NECOCLI</option>
          <option value='NEIRA'>NEIRA</option>
          <option value='NEIVA'>NEIVA</option>
          <option value='NEMOCON'>NEMOCON</option>
          <option value='NILO'>NILO</option>
          <option value='NIMAIMA'>NIMAIMA</option>
          <option value='NOBSA'>NOBSA</option>
          <option value='NOCAIMA'>NOCAIMA</option>
          <option value='NORCASIA'>NORCASIA</option>
          <option value='NOROSI'>NOROSI</option>
          <option value='NOVITA'>NOVITA</option>
          <option value='NUEVA GRANADA'>NUEVA GRANADA</option>
          <option value='NUEVO COLON'>NUEVO COLON</option>
          <option value='NUNCHIA'>NUNCHIA</option>
          <option value='NUQUI'>NUQUI</option>
          <option value='OBANDO'>OBANDO</option>
          <option value='OCAMONTE'>OCAMONTE</option>
          <option value='OCAÑA'>OCAÑA</option>
          <option value='OIBA'>OIBA</option>
          <option value='OICATA'>OICATA</option>
          <option value='OLAYA'>OLAYA</option>
          <option value='OLAYA HERRERA'>OLAYA HERRERA</option>
          <option value='ONZAGA'>ONZAGA</option>
          <option value='OPORAPA'>OPORAPA</option>
          <option value='ORITO'>ORITO</option>
          <option value='OROCUE'>OROCUE</option>
          <option value='ORTEGA'>ORTEGA</option>
          <option value='OSPINA'>OSPINA</option>
          <option value='OTANCHE'>OTANCHE</option>
          <option value='OVEJAS'>OVEJAS</option>
          <option value='PACHAVITA'>PACHAVITA</option>
          <option value='PACHO'>PACHO</option>
          <option value='PACOA'>PACOA</option>
          <option value='PACORA'>PACORA</option>
          <option value='PADILLA'>PADILLA</option>
          <option value='PAEZ'>PAEZ</option>
          <option value='PAEZ'>PAEZ</option>
          <option value='PAICOL'>PAICOL</option>
          <option value='PAILITAS'>PAILITAS</option>
          <option value='PAIME'>PAIME</option>
          <option value='PAIPA'>PAIPA</option>
          <option value='PAJARITO'>PAJARITO</option>
          <option value='PALERMO'>PALERMO</option>
          <option value='PALESTINA'>PALESTINA</option>
          <option value='PALESTINA'>PALESTINA</option>
          <option value='PALMAR'>PALMAR</option>
          <option value='PALMAR DE VARELA'>PALMAR DE VARELA</option>
          <option value='PALMAS DEL SOCORRO'>PALMAS DEL SOCORRO</option>
          <option value='PALMIRA'>PALMIRA</option>
          <option value='PALMITO'>PALMITO</option>
          <option value='PALOCABILDO'>PALOCABILDO</option>
          <option value='PAMPLONA'>PAMPLONA</option>
          <option value='PAMPLONITA'>PAMPLONITA</option>
          <option value='PANA PANA'>PANA PANA</option>
          <option value='PANDI'>PANDI</option>
          <option value='PANQUEBA'>PANQUEBA</option>
          <option value='PAPUNAUA'>PAPUNAUA</option>
          <option value='PARAMO'>PARAMO</option>
          <option value='PARATEBUENO'>PARATEBUENO</option>
          <option value='PASCA'>PASCA</option>
          <option value='PASTO'>PASTO</option>
          <option value='PATIA'>PATIA</option>
          <option value='PAUNA'>PAUNA</option>
          <option value='PAYA'>PAYA</option>
          <option value='PAZ DE ARIPORO'>PAZ DE ARIPORO</option>
          <option value='PAZ DE RIO'>PAZ DE RIO</option>
          <option value='PEÐOL'>PEÐOL</option>
          <option value='PEDRAZA'>PEDRAZA</option>
          <option value='PELAYA'>PELAYA</option>
          <option value='PENSILVANIA'>PENSILVANIA</option>
          <option value='PEQUE'>PEQUE</option>
          <option value='PEREIRA'>PEREIRA</option>
          <option value='PESCA'>PESCA</option>
          <option value='PIAMONTE'>PIAMONTE</option>
          <option value='PIEDECUESTA'>PIEDECUESTA</option>
          <option value='PIEDRAS'>PIEDRAS</option>
          <option value='PIENDAMO'>PIENDAMO</option>
          <option value='PIJAO'>PIJAO</option>
          <option value='PIJIÑO DEL CARMEN'>PIJIÑO DEL CARMEN</option>
          <option value='PINCHOTE'>PINCHOTE</option>
          <option value='PINILLOS'>PINILLOS</option>
          <option value='PIOJO'>PIOJO</option>
          <option value='PISBA'>PISBA</option>
          <option value='PITAL'>PITAL</option>
          <option value='PITALITO'>PITALITO</option>
          <option value='PIVIJAY'>PIVIJAY</option>
          <option value='PLANADAS'>PLANADAS</option>
          <option value='PLANETA RICA'>PLANETA RICA</option>
          <option value='PLATO'>PLATO</option>
          <option value='POLICARPA'>POLICARPA</option>
          <option value='POLONUEVO'>POLONUEVO</option>
          <option value='PONEDERA'>PONEDERA</option>
          <option value='POPAYAN'>POPAYAN</option>
          <option value='PORE'>PORE</option>
          <option value='POTOSI'>POTOSI</option>
          <option value='PRADERA'>PRADERA</option>
          <option value='PRADO'>PRADO</option>
          <option value='PROVIDENCIA'>PROVIDENCIA</option>
          <option value='PROVIDENCIA'>PROVIDENCIA</option>
          <option value='PUEBLO BELLO'>PUEBLO BELLO</option>
          <option value='PUEBLO NUEVO'>PUEBLO NUEVO</option>
          <option value='PUEBLO RICO'>PUEBLO RICO</option>
          <option value='PUEBLORRICO'>PUEBLORRICO</option>
          <option value='PUEBLOVIEJO'>PUEBLOVIEJO</option>
          <option value='PUENTE NACIONAL'>PUENTE NACIONAL</option>
          <option value='PUERRES'>PUERRES</option>
          <option value='PUERTO ALEGRIA'>PUERTO ALEGRIA</option>
          <option value='PUERTO ARICA'>PUERTO ARICA</option>
          <option value='PUERTO ASIS'>PUERTO ASIS</option>
          <option value='PUERTO BERRIO'>PUERTO BERRIO</option>
          <option value='PUERTO BOYACA'>PUERTO BOYACA</option>
          <option value='PUERTO CAICEDO'>PUERTO CAICEDO</option>
          <option value='PUERTO CARREÑO'>PUERTO CARREÑO</option>
          <option value='PUERTO COLOMBIA'>PUERTO COLOMBIA</option>
          <option value='PUERTO COLOMBIA'>PUERTO COLOMBIA</option>
          <option value='PUERTO CONCORDIA'>PUERTO CONCORDIA</option>
          <option value='PUERTO ESCONDIDO'>PUERTO ESCONDIDO</option>
          <option value='PUERTO GAITAN'>PUERTO GAITAN</option>
          <option value='PUERTO GUZMAN'>PUERTO GUZMAN</option>
          <option value='PUERTO LIBERTADOR'>PUERTO LIBERTADOR</option>
          <option value='PUERTO LLERAS'>PUERTO LLERAS</option>
          <option value='PUERTO LOPEZ'>PUERTO LOPEZ</option>
          <option value='PUERTO NARE'>PUERTO NARE</option>
          <option value='PUERTO NARIÑO'>PUERTO NARIÑO</option>
          <option value='PUERTO PARRA'>PUERTO PARRA</option>
          <option value='PUERTO RICO'>PUERTO RICO</option>
          <option value='PUERTO RICO'>PUERTO RICO</option>
          <option value='PUERTO RONDON'>PUERTO RONDON</option>
          <option value='PUERTO SALGAR'>PUERTO SALGAR</option>
          <option value='PUERTO SANTANDER'>PUERTO SANTANDER</option>
          <option value='PUERTO SANTANDER'>PUERTO SANTANDER</option>
          <option value='PUERTO TEJADA'>PUERTO TEJADA</option>
          <option value='PUERTO TRIUNFO'>PUERTO TRIUNFO</option>
          <option value='PUERTO WILCHES'>PUERTO WILCHES</option>
          <option value='PULI'>PULI</option>
          <option value='PUPIALES'>PUPIALES</option>
          <option value='PURACE'>PURACE</option>
          <option value='PURIFICACION'>PURIFICACION</option>
          <option value='PURISIMA'>PURISIMA</option>
          <option value='QUEBRADANEGRA'>QUEBRADANEGRA</option>
          <option value='QUETAME'>QUETAME</option>
          <option value='QUIBDO'>QUIBDO</option>
          <option value='QUIMBAYA'>QUIMBAYA</option>
          <option value='QUINCHIA'>QUINCHIA</option>
          <option value='QUIPAMA'>QUIPAMA</option>
          <option value='QUIPILE'>QUIPILE</option>
          <option value='RAGONVALIA'>RAGONVALIA</option>
          <option value='RAMIRIQUI'>RAMIRIQUI</option>
          <option value='RAQUIRA'>RAQUIRA</option>
          <option value='RECETOR'>RECETOR</option>
          <option value='REGIDOR'>REGIDOR</option>
          <option value='REMEDIOS'>REMEDIOS</option>
          <option value='REMOLINO'>REMOLINO</option>
          <option value='REPELON'>REPELON</option>
          <option value='RESTREPO'>RESTREPO</option>
          <option value='RESTREPO'>RESTREPO</option>
          <option value='RETIRO'>RETIRO</option>
          <option value='RICAURTE'>RICAURTE</option>
          <option value='RICAURTE'>RICAURTE</option>
          <option value='RIO DE ORO'>RIO DE ORO</option>
          <option value='RIO IRO'>RIO IRO</option>
          <option value='RIO QUITO'>RIO QUITO</option>
          <option value='RIO VIEJO'>RIO VIEJO</option>
          <option value='RIOBLANCO'>RIOBLANCO</option>
          <option value='RIOFRIO'>RIOFRIO</option>
          <option value='RIOHACHA'>RIOHACHA</option>
          <option value='RIONEGRO'>RIONEGRO</option>
          <option value='RIONEGRO'>RIONEGRO</option>
          <option value='RIOSUCIO'>RIOSUCIO</option>
          <option value='RIOSUCIO'>RIOSUCIO</option>
          <option value='RISARALDA'>RISARALDA</option>
          <option value='RIVERA'>RIVERA</option>
          <option value='ROBERTO PAYAN'>ROBERTO PAYAN</option>
          <option value='ROLDANILLO'>ROLDANILLO</option>
          <option value='RONCESVALLES'>RONCESVALLES</option>
          <option value='RONDON'>RONDON</option>
          <option value='ROSAS'>ROSAS</option>
          <option value='ROVIRA'>ROVIRA</option>
          <option value='SABANA DE TORRES'>SABANA DE TORRES</option>
          <option value='SABANAGRANDE'>SABANAGRANDE</option>
          <option value='SABANALARGA'>SABANALARGA</option>
          <option value='SABANALARGA'>SABANALARGA</option>
          <option value='SABANALARGA'>SABANALARGA</option>
          <option value='SABANAS DE SAN ANGEL'>SABANAS DE SAN ANGEL</option>
          <option value='SABANETA'>SABANETA</option>
          <option value='SABOYA'>SABOYA</option>
          <option value='SACAMA'>SACAMA</option>
          <option value='SACHICA'>SACHICA</option>
          <option value='SAHAGUN'>SAHAGUN</option>
          <option value='SALADOBLANCO'>SALADOBLANCO</option>
          <option value='SALAMINA'>SALAMINA</option>
          <option value='SALAMINA'>SALAMINA</option>
          <option value='SALAZAR'>SALAZAR</option>
          <option value='SALDAÑA'>SALDAÑA</option>
          <option value='SALENTO'>SALENTO</option>
          <option value='SALGAR'>SALGAR</option>
          <option value='SAMACA'>SAMACA</option>
          <option value='SAMANA'>SAMANA</option>
          <option value='SAMANIEGO'>SAMANIEGO</option>
          <option value='SAMPUES'>SAMPUES</option>
          <option value='SAN AGUSTIN'>SAN AGUSTIN</option>
          <option value='SAN ALBERTO'>SAN ALBERTO</option>
          <option value='SAN ANDRES'>SAN ANDRES</option>
          <option value='SAN ANDRES'>SAN ANDRES</option>
          <option value='SAN ANDRES DE CUERQUIA'>SAN ANDRES DE CUERQUIA</option>
          <option value='SAN ANDRES DE TUMACO'>SAN ANDRES DE TUMACO</option>
          <option value='SAN ANDRES SOTAVENTO'>SAN ANDRES SOTAVENTO</option>
          <option value='SAN ANTERO'>SAN ANTERO</option>
          <option value='SAN ANTONIO'>SAN ANTONIO</option>
          <option value='SAN ANTONIO DEL TEQUENDAMA'>SAN ANTONIO DEL TEQUENDAMA</option>
          <option value='SAN BENITO'>SAN BENITO</option>
          <option value='SAN BENITO ABAD'>SAN BENITO ABAD</option>
          <option value='SAN BERNARDO'>SAN BERNARDO</option>
          <option value='SAN BERNARDO'>SAN BERNARDO</option>
          <option value='SAN BERNARDO DEL VIENTO'>SAN BERNARDO DEL VIENTO</option>
          <option value='SAN CALIXTO'>SAN CALIXTO</option>
          <option value='SAN CARLOS'>SAN CARLOS</option>
          <option value='SAN CARLOS'>SAN CARLOS</option>
          <option value='SAN CARLOS DE GUAROA'>SAN CARLOS DE GUAROA</option>
          <option value='SAN CAYETANO'>SAN CAYETANO</option>
          <option value='SAN CAYETANO'>SAN CAYETANO</option>
          <option value='SAN CRISTOBAL'>SAN CRISTOBAL</option>
          <option value='SAN DIEGO'>SAN DIEGO</option>
          <option value='SAN EDUARDO'>SAN EDUARDO</option>
          <option value='SAN ESTANISLAO'>SAN ESTANISLAO</option>
          <option value='SAN FELIPE'>SAN FELIPE</option>
          <option value='SAN FERNANDO'>SAN FERNANDO</option>
          <option value='SAN FRANCISCO'>SAN FRANCISCO</option>
          <option value='SAN FRANCISCO'>SAN FRANCISCO</option>
          <option value='SAN FRANCISCO'>SAN FRANCISCO</option>
          <option value='SAN GIL'>SAN GIL</option>
          <option value='SAN JACINTO'>SAN JACINTO</option>
          <option value='SAN JACINTO DEL CAUCA'>SAN JACINTO DEL CAUCA</option>
          <option value='SAN JERONIMO'>SAN JERONIMO</option>
          <option value='SAN JOAQUIN'>SAN JOAQUIN</option>
          <option value='SAN JOSE'>SAN JOSE</option>
          <option value='SAN JOSE DE LA MONTAÑA'>SAN JOSE DE LA MONTAÑA</option>
          <option value='SAN JOSE DE MIRANDA'>SAN JOSE DE MIRANDA</option>
          <option value='SAN JOSE DE PARE'>SAN JOSE DE PARE</option>
          <option value='SAN JOSE DEL FRAGUA'>SAN JOSE DEL FRAGUA</option>
          <option value='SAN JOSE DEL GUAVIARE'>SAN JOSE DEL GUAVIARE</option>
          <option value='SAN JOSE DEL PALMAR'>SAN JOSE DEL PALMAR</option>
          <option value='SAN JUAN DE ARAMA'>SAN JUAN DE ARAMA</option>
          <option value='SAN JUAN DE BETULIA'>SAN JUAN DE BETULIA</option>
          <option value='SAN JUAN DE RIO SECO'>SAN JUAN DE RIO SECO</option>
          <option value='SAN JUAN DE URABA'>SAN JUAN DE URABA</option>
          <option value='SAN JUAN DEL CESAR'>SAN JUAN DEL CESAR</option>
          <option value='SAN JUAN NEPOMUCENO'>SAN JUAN NEPOMUCENO</option>
          <option value='SAN JUANITO'>SAN JUANITO</option>
          <option value='SAN LORENZO'>SAN LORENZO</option>
          <option value='SAN LUIS'>SAN LUIS</option>
          <option value='SAN LUIS'>SAN LUIS</option>
          <option value='SAN LUIS DE GACENO'>SAN LUIS DE GACENO</option>
          <option value='SAN LUIS DE PALENQUE'>SAN LUIS DE PALENQUE</option>
          <option value='SAN LUIS DE SINCE'>SAN LUIS DE SINCE</option>
          <option value='SAN MARCOS'>SAN MARCOS</option>
          <option value='SAN MARTIN'>SAN MARTIN</option>
          <option value='SAN MARTIN'>SAN MARTIN</option>
          <option value='SAN MARTIN DE LOBA'>SAN MARTIN DE LOBA</option>
          <option value='SAN MATEO'>SAN MATEO</option>
          <option value='SAN MIGUEL'>SAN MIGUEL</option>
          <option value='SAN MIGUEL'>SAN MIGUEL</option>
          <option value='SAN MIGUEL DE SEMA'>SAN MIGUEL DE SEMA</option>
          <option value='SAN ONOFRE'>SAN ONOFRE</option>
          <option value='SAN PABLO'>SAN PABLO</option>
          <option value='SAN PABLO'>SAN PABLO</option>
          <option value='SAN PABLO DE BORBUR'>SAN PABLO DE BORBUR</option>
          <option value='SAN PEDRO'>SAN PEDRO</option>
          <option value='SAN PEDRO'>SAN PEDRO</option>
          <option value='SAN PEDRO'>SAN PEDRO</option>
          <option value='SAN PEDRO DE CARTAGO'>SAN PEDRO DE CARTAGO</option>
          <option value='SAN PEDRO DE URABA'>SAN PEDRO DE URABA</option>
          <option value='SAN PELAYO'>SAN PELAYO</option>
          <option value='SAN RAFAEL'>SAN RAFAEL</option>
          <option value='SAN ROQUE'>SAN ROQUE</option>
          <option value='SAN SEBASTIAN'>SAN SEBASTIAN</option>
          <option value='SAN SEBASTIAN DE BUENAVISTA'>SAN SEBASTIAN DE BUENAVISTA</option>
          <option value='SAN VICENTE'>SAN VICENTE</option>
          <option value='SAN VICENTE DE CHUCURI'>SAN VICENTE DE CHUCURI</option>
          <option value='SAN VICENTE DEL CAGUAN'>SAN VICENTE DEL CAGUAN</option>
          <option value='SAN ZENON'>SAN ZENON</option>
          <option value='SANDONA'>SANDONA</option>
          <option value='SANTA ANA'>SANTA ANA</option>
          <option value='SANTA BARBARA'>SANTA BARBARA</option>
          <option value='SANTA BARBARA'>SANTA BARBARA</option>
          <option value='SANTA BARBARA'>SANTA BARBARA</option>
          <option value='SANTA BARBARA DE PINTO'>SANTA BARBARA DE PINTO</option>
          <option value='SANTA CATALINA'>SANTA CATALINA</option>
          <option value='SANTA HELENA DEL OPON'>SANTA HELENA DEL OPON</option>
          <option value='SANTA ISABEL'>SANTA ISABEL</option>
          <option value='SANTA LUCIA'>SANTA LUCIA</option>
          <option value='SANTA MARIA'>SANTA MARIA</option>
          <option value='SANTA MARIA'>SANTA MARIA</option>
          <option value='SANTA MARTA'>SANTA MARTA</option>
          <option value='SANTA ROSA'>SANTA ROSA</option>
          <option value='SANTA ROSA'>SANTA ROSA</option>
          <option value='SANTA ROSA DE CABAL'>SANTA ROSA DE CABAL</option>
          <option value='SANTA ROSA DE OSOS'>SANTA ROSA DE OSOS</option>
          <option value='SANTA ROSA DE VITERBO'>SANTA ROSA DE VITERBO</option>
          <option value='SANTA ROSA DEL SUR'>SANTA ROSA DEL SUR</option>
          <option value='SANTA ROSALIA'>SANTA ROSALIA</option>
          <option value='SANTA SOFIA'>SANTA SOFIA</option>
          <option value='SANTACRUZ'>SANTACRUZ</option>
          <option value='SANTAFE DE ANTIOQUIA'>SANTAFE DE ANTIOQUIA</option>
          <option value='SANTANA'>SANTANA</option>
          <option value='SANTANDER DE QUILICHAO'>SANTANDER DE QUILICHAO</option>
          <option value='SANTIAGO'>SANTIAGO</option>
          <option value='SANTIAGO'>SANTIAGO</option>
          <option value='SANTIAGO DE TOLU'>SANTIAGO DE TOLU</option>
          <option value='SANTO DOMINGO'>SANTO DOMINGO</option>
          <option value='SANTO TOMAS'>SANTO TOMAS</option>
          <option value='SANTUARIO'>SANTUARIO</option>
          <option value='SAPUYES'>SAPUYES</option>
          <option value='SARAVENA'>SARAVENA</option>
          <option value='SARDINATA'>SARDINATA</option>
          <option value='SASAIMA'>SASAIMA</option>
          <option value='SATIVANORTE'>SATIVANORTE</option>
          <option value='SATIVASUR'>SATIVASUR</option>
          <option value='SEGOVIA'>SEGOVIA</option>
          <option value='SESQUILE'>SESQUILE</option>
          <option value='SEVILLA'>SEVILLA</option>
          <option value='SIACHOQUE'>SIACHOQUE</option>
          <option value='SIBATE'>SIBATE</option>
          <option value='SIBUNDOY'>SIBUNDOY</option>
          <option value='SILOS'>SILOS</option>
          <option value='SILVANIA'>SILVANIA</option>
          <option value='SILVIA'>SILVIA</option>
          <option value='SIMACOTA'>SIMACOTA</option>
          <option value='SIMIJACA'>SIMIJACA</option>
          <option value='SIMITI'>SIMITI</option>
          <option value='SINCELEJO'>SINCELEJO</option>
          <option value='SIPI'>SIPI</option>
          <option value='SITIONUEVO'>SITIONUEVO</option>
          <option value='SOACHA'>SOACHA</option>
          <option value='SOATA'>SOATA</option>
          <option value='SOCHA'>SOCHA</option>
          <option value='SOCORRO'>SOCORRO</option>
          <option value='SOCOTA'>SOCOTA</option>
          <option value='SOGAMOSO'>SOGAMOSO</option>
          <option value='SOLANO'>SOLANO</option>
          <option value='SOLEDAD'>SOLEDAD</option>
          <option value='SOLITA'>SOLITA</option>
          <option value='SOMONDOCO'>SOMONDOCO</option>
          <option value='SONSON'>SONSON</option>
          <option value='SOPETRAN'>SOPETRAN</option>
          <option value='SOPLAVIENTO'>SOPLAVIENTO</option>
          <option value='SOPO'>SOPO</option>
          <option value='SORA'>SORA</option>
          <option value='SORACA'>SORACA</option>
          <option value='SOTAQUIRA'>SOTAQUIRA</option>
          <option value='SOTARA'>SOTARA</option>
          <option value='SUAITA'>SUAITA</option>
          <option value='SUAN'>SUAN</option>
          <option value='SUAREZ'>SUAREZ</option>
          <option value='SUAREZ'>SUAREZ</option>
          <option value='SUAZA'>SUAZA</option>
          <option value='SUBACHOQUE'>SUBACHOQUE</option>
          <option value='SUCRE'>SUCRE</option>
          <option value='SUCRE'>SUCRE</option>
          <option value='SUCRE'>SUCRE</option>
          <option value='SUESCA'>SUESCA</option>
          <option value='SUPATA'>SUPATA</option>
          <option value='SUPIA'>SUPIA</option>
          <option value='SURATA'>SURATA</option>
          <option value='SUSA'>SUSA</option>
          <option value='SUSACON'>SUSACON</option>
          <option value='SUTAMARCHAN'>SUTAMARCHAN</option>
          <option value='SUTATAUSA'>SUTATAUSA</option>
          <option value='SUTATENZA'>SUTATENZA</option>
          <option value='TABIO'>TABIO</option>
          <option value='TADO'>TADO</option>
          <option value='TALAIGUA NUEVO'>TALAIGUA NUEVO</option>
          <option value='TAMALAMEQUE'>TAMALAMEQUE</option>
          <option value='TAMARA'>TAMARA</option>
          <option value='TAME'>TAME</option>
          <option value='TAMESIS'>TAMESIS</option>
          <option value='TAMINANGO'>TAMINANGO</option>
          <option value='TANGUA'>TANGUA</option>
          <option value='TARAIRA'>TARAIRA</option>
          <option value='TARAPACA'>TARAPACA</option>
          <option value='TARAZA'>TARAZA</option>
          <option value='TARQUI'>TARQUI</option>
          <option value='TARSO'>TARSO</option>
          <option value='TASCO'>TASCO</option>
          <option value='TAURAMENA'>TAURAMENA</option>
          <option value='TAUSA'>TAUSA</option>
          <option value='TELLO'>TELLO</option>
          <option value='TENA'>TENA</option>
          <option value='TENERIFE'>TENERIFE</option>
          <option value='TENJO'>TENJO</option>
          <option value='TENZA'>TENZA</option>
          <option value='TEORAMA'>TEORAMA</option>
          <option value='TERUEL'>TERUEL</option>
          <option value='TESALIA'>TESALIA</option>
          <option value='TIBACUY'>TIBACUY</option>
          <option value='TIBANA'>TIBANA</option>
          <option value='TIBASOSA'>TIBASOSA</option>
          <option value='TIBIRITA'>TIBIRITA</option>
          <option value='TIBU'>TIBU</option>
          <option value='TIERRALTA'>TIERRALTA</option>
          <option value='TIMANA'>TIMANA</option>
          <option value='TIMBIO'>TIMBIO</option>
          <option value='TIMBIQUI'>TIMBIQUI</option>
          <option value='TINJACA'>TINJACA</option>
          <option value='TIPACOQUE'>TIPACOQUE</option>
          <option value='TIQUISIO'>TIQUISIO</option>
          <option value='TITIRIBI'>TITIRIBI</option>
          <option value='TOCA'>TOCA</option>
          <option value='TOCAIMA'>TOCAIMA</option>
          <option value='TOCANCIPA'>TOCANCIPA</option>
          <option value='TOGsI'>TOGsI</option>
          <option value='TOLEDO'>TOLEDO</option>
          <option value='TOLEDO'>TOLEDO</option>
          <option value='TOLU VIEJO'>TOLU VIEJO</option>
          <option value='TONA'>TONA</option>
          <option value='TOPAGA'>TOPAGA</option>
          <option value='TOPAIPI'>TOPAIPI</option>
          <option value='TORIBIO'>TORIBIO</option>
          <option value='TORO'>TORO</option>
          <option value='TOTA'>TOTA</option>
          <option value='TOTORO'>TOTORO</option>
          <option value='TRINIDAD'>TRINIDAD</option>
          <option value='TRUJILLO'>TRUJILLO</option>
          <option value='TUBARA'>TUBARA</option>
          <option value='TULUA'>TULUA</option>
          <option value='TUNJA'>TUNJA</option>
          <option value='TUNUNGUA'>TUNUNGUA</option>
          <option value='TUQUERRES'>TUQUERRES</option>
          <option value='TURBACO'>TURBACO</option>
          <option value='TURBANA'>TURBANA</option>
          <option value='TURBO'>TURBO</option>
          <option value='TURMEQUE'>TURMEQUE</option>
          <option value='TUTA'>TUTA</option>
          <option value='TUTAZA'>TUTAZA</option>
          <option value='UBALA'>UBALA</option>
          <option value='UBAQUE'>UBAQUE</option>
          <option value='ULLOA'>ULLOA</option>
          <option value='UMBITA'>UMBITA</option>
          <option value='UNE'>UNE</option>
          <option value='UNGUIA'>UNGUIA</option>
          <option value='UNION PANAMERICANA'>UNION PANAMERICANA</option>
          <option value='URAMITA'>URAMITA</option>
          <option value='URIBE'>URIBE</option>
          <option value='URIBIA'>URIBIA</option>
          <option value='URRAO'>URRAO</option>
          <option value='URUMITA'>URUMITA</option>
          <option value='USIACURI'>USIACURI</option>
          <option value='UTICA'>UTICA</option>
          <option value='VALDIVIA'>VALDIVIA</option>
          <option value='VALENCIA'>VALENCIA</option>
          <option value='VALLE DE SAN JOSE'>VALLE DE SAN JOSE</option>
          <option value='VALLE DE SAN JUAN'>VALLE DE SAN JUAN</option>
          <option value='VALLE DEL GUAMUEZ'>VALLE DEL GUAMUEZ</option>
          <option value='VALLEDUPAR'>VALLEDUPAR</option>
          <option value='VALPARAISO'>VALPARAISO</option>
          <option value='VALPARAISO'>VALPARAISO</option>
          <option value='VEGACHI'>VEGACHI</option>
          <option value='VELEZ'>VELEZ</option>
          <option value='VENADILLO'>VENADILLO</option>
          <option value='VENECIA'>VENECIA</option>
          <option value='VENECIA'>VENECIA</option>
          <option value='VENTAQUEMADA'>VENTAQUEMADA</option>
          <option value='VERGARA'>VERGARA</option>
          <option value='VERSALLES'>VERSALLES</option>
          <option value='VETAS'>VETAS</option>
          <option value='VIANI'>VIANI</option>
          <option value='VICTORIA'>VICTORIA</option>
          <option value='VIGIA DEL FUERTE'>VIGIA DEL FUERTE</option>
          <option value='VIJES'>VIJES</option>
          <option value='VILLA CARO'>VILLA CARO</option>
          <option value='VILLA DE LEYVA'>VILLA DE LEYVA</option>
          <option value='VILLA DE SAN DIEGO DE UBATE'>VILLA DE SAN DIEGO DE UBATE</option>
          <option value='VILLA DEL ROSARIO'>VILLA DEL ROSARIO</option>
          <option value='VILLA RICA'>VILLA RICA</option>
          <option value='VILLAGARZON'>VILLAGARZON</option>
          <option value='VILLAGOMEZ'>VILLAGOMEZ</option>
          <option value='VILLAHERMOSA'>VILLAHERMOSA</option>
          <option value='VILLAMARIA'>VILLAMARIA</option>
          <option value='VILLANUEVA'>VILLANUEVA</option>
          <option value='VILLANUEVA'>VILLANUEVA</option>
          <option value='VILLANUEVA'>VILLANUEVA</option>
          <option value='VILLANUEVA'>VILLANUEVA</option>
          <option value='VILLAPINZON'>VILLAPINZON</option>
          <option value='VILLARRICA'>VILLARRICA</option>
          <option value='VILLAVICENCIO'>VILLAVICENCIO</option>
          <option value='VILLAVIEJA'>VILLAVIEJA</option>
          <option value='VILLETA'>VILLETA</option>
          <option value='VIOTA'>VIOTA</option>
          <option value='VIRACACHA'>VIRACACHA</option>
          <option value='VISTAHERMOSA'>VISTAHERMOSA</option>
          <option value='VITERBO'>VITERBO</option>
          <option value='YACOPI'>YACOPI</option>
          <option value='YACUANQUER'>YACUANQUER</option>
          <option value='YAGUARA'>YAGUARA</option>
          <option value='YALI'>YALI</option>
          <option value='YARUMAL'>YARUMAL</option>
          <option value='YAVARATE'>YAVARATE</option>
          <option value='YOLOMBO'>YOLOMBO</option>
          <option value='YONDO'>YONDO</option>
          <option value='YOPAL'>YOPAL</option>
          <option value='YOTOCO'>YOTOCO</option>
          <option value='YUMBO'>YUMBO</option>
          <option value='ZAMBRANO'>ZAMBRANO</option>
          <option value='ZAPATOCA'>ZAPATOCA</option>
          <option value='ZAPAYAN'>ZAPAYAN</option>
          <option value='ZARAGOZA'>ZARAGOZA</option>
          <option value='ZARZAL'>ZARZAL</option>
          <option value='ZETAQUIRA'>ZETAQUIRA</option>
          <option value='ZIPACON'>ZIPACON</option>
          <option value='ZIPAQUIRA'>ZIPAQUIRA</option>
          <option value='ZONA BANANERA'>ZONA BANANERA</option>
        </select>
        <input type="text" class="form-control" name="ciudad" id="ciudad" aria-describedby="emailHelp" placeholder="" required="required" style="display:none;">      
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Dirección</label>
        <input type="text" class="form-control" name="direccion" aria-describedby="emailHelp" placeholder="" required="required">      
      </div>    
      <div class="form-group">
        <label for="exampleInputEmail1">Código Postal</label>
        <input type="text" class="form-control" name="cod_postal" aria-describedby="emailHelp" placeholder="" required="required">      
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Teléfono Fijo</label>
        <input type="text" class="form-control" name="telefono" aria-describedby="emailHelp" placeholder="">      
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Teléfono Móvil</label>
        <input type="text" class="form-control" name="telefono_m" aria-describedby="emailHelp" placeholder="" required="required">      
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Contraseña</label>
        <input type="password" class="form-control" name="password" aria-describedby="emailHelp" placeholder="" required="required">      
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Repetir contraseña</label>
        <input type="password" class="form-control" name="password2" aria-describedby="emailHelp" placeholder="" required="required">      
      </div>
      <center>
        <button type="submit" name="createUser" class="btn btn-primary">CREAR CUENTA</button>
      </center>
    </form>
  </div>
</div>

<?php include "footer.php" ?>